Added blueprint check
ciena-frost/ember-frost-sort pull request #60
Opened 2017-04-19 16:08 UTC by dafortin

### This project uses [semver](semver.org), please check the scope of this pr:

- [ ] #none# - documentation fixes and/or test additions
- [x] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG
* **Added** blueprint check

2017-04-20 19:36 UTC, rox163 commented on blueprints/ember-frost-sort/index.js
> +      {name: 'ember-computed-decorators', target: '~0.2.2'},
can we move to 0.3.x for this addon?

2017-04-21 15:26 UTC, rox163 commented
:+1:

2017-04-21 15:55 UTC, sglanzer commented on blueprints/ember-frost-sort/index.js
> +      {name: 'ember-elsewhere', target: '~0.4.1'},
Does `sort` use `elsewhere` or is that just a factor of using the select?

2017-04-21 15:55 UTC, sglanzer commented on blueprints/ember-frost-sort/index.js
> +      {name: 'ember-prop-types', target: '^3.10.2'}
Will `hook`, `prop-types` and `computed-decorators` come in from `core`?

2017-04-21 15:57 UTC, sglanzer-fire requested changes
I'd just like confirmation if the nested installation from `core` will cover the other addons or if the need to be explicit

2017-04-21 15:59 UTC, dafortin commented on blueprints/ember-frost-sort/index.js
> +      {name: 'ember-elsewhere', target: '~0.4.1'},
no I will remove it from here.

2017-04-21 16:00 UTC, dafortin commented on blueprints/ember-frost-sort/index.js
> +      {name: 'ember-prop-types', target: '^3.10.2'}
They will, but this addon is also using those so I'm expecting that we need those here.

2017-04-21 16:05 UTC, sglanzer commented on blueprints/ember-frost-sort/index.js
> +      {name: 'ember-prop-types', target: '^3.10.2'}
If core handles the installation then I believe you'll only need `core` - the hook here will only determine installation, not consumption.  Consumption would be a factor of the resolver and `ember-cli` registering the addon, which should happen automagically if the packages are present

Give it a shot, but I'm pretty sure I'm correct about this

2017-04-21 16:15 UTC, dafortin commented on blueprints/ember-frost-sort/index.js
> +      {name: 'ember-prop-types', target: '^3.10.2'}
Now I'm curious :P I will try it for sure :)

2017-04-21 16:49 UTC, rox163 commented
:+1:

2017-04-21 17:03 UTC, sglanzer-fire approved these changes

2017-04-21 17:51 UTC, merged